name: Code Auto Format
run-name: Code Format by ${{ github.actor }}
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: ls .
      - uses: actions/checkout@v3
      - run: ls .
      - name: Code Format
        run: |
          java -jar ./programs/ktlint.jar -F app/src/*.kt
      - run: echo "Code formatted status ${{ job.status }}."