name: GitHub Actions Demo
run-name: Code Format by ${{ github.actor }}
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: ls ./programs/
      - name: Code Format
        run: |
          java -jar ./programs/ktlint.jar -F app/src/*.kt
      - run: echo "Code formatted status ${{ job.status }}."