name: Code Auto Format
run-name: Code Format by ${{ github.actor }}
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Code Format
        run: |
          java -jar ./programs/ktlint.jar -F ./app/**.kt || true
          if git diff-index --quiet HEAD --; then
              echo "Code formatting matched"
          else
              git add .
              git commit -m "action: auto-formatting"
              git push
          fi
      - run: echo "Code formatted status ${{ job.status }}."